import os

import sentry_sdk

VERSION = "2025.06.02"

DISCORD_TOKEN = os.getenv("DISCORD_TOKEN")
SENTRY_DSN = os.getenv("SENTRY_DSN")

GUILD = os.getenv("GUILD")
OWNER = os.getenv("OWNER")

ROLE_VIDEOS = os.getenv("ROLE_NOTIF_VIDEOS")
ROLE_TIKTOK = os.getenv("ROLE_NOTIF_TIKTOK")
ROLE_FEDI = os.getenv("ROLE_NOTIF_FEDI")
ROLE_NSFW = os.getenv("ROLE_NSFW")

CHANNEL_GENERAL = os.getenv("CHANNEL_GENERAL")
CHANNEL_MEMES = os.getenv("CHANNEL_MEMES")
CHANNEL_MEDIA = os.getenv("CHANNEL_MEDIA")

CHANNEL_NEW_VIDEOS = os.getenv("CHANNEL_NEW_VIDEOS")
CHANNEL_NEW_FEDI = os.getenv("CHANNEL_NEW_FEDI")
CHANNEL_NEW_TIKTOK = os.getenv("CHANNEL_NEW_TIKTOK")

CHANNEL_MODERATION = os.getenv("CHANNEL_MODERATION")

FEDI_INSTANCE = os.getenv("FEDI_INSTANCE")
FEDI_USER_ID = os.getenv("FEDI_USER_ID")
FEDI_TOKEN = os.getenv("FEDI_TOKEN")

FORGEJO_INSTANCE = os.getenv("FORGEJO_INSTANCE")
FORGEJO_DEFAULT_USER = os.getenv("FORGEJO_DEFAULT_USER")
FORGEJO_TOKEN = os.getenv("FORGEJO_TOKEN")

YT_LINK = os.getenv("YT_LINK")
TT_LINK = os.getenv("TT_LINK")

WEB_SERVER_URL = os.getenv("WEB_SERVER_URL")
WEB_SERVER_CODE = os.getenv("WEB_SERVER_CODE")

def validate_values(l: dict[str, str | None]):
    for k, v in l.items():
        if v is None:
            print(f"CONSTANTS: The constant value for {k} is NOT set!")
            sentry_sdk.capture_message(f"CONSTANTS: The constant value for {k} is NOT set!")

validate_values({
    'DISCORD_TOKEN': DISCORD_TOKEN,
    'SENTRY_DSN': SENTRY_DSN,
    'GUILD': GUILD,
    'OWNER': OWNER,
    'ROLE_VIDEOS': ROLE_VIDEOS,
    'ROLE_TIKTOK': ROLE_TIKTOK,
    'ROLE_FEDI': ROLE_FEDI,
    'ROLE_NSFW': ROLE_NSFW,
    'CHANNEL_GENERAL': CHANNEL_GENERAL,
    'CHANNEL_MEMES': CHANNEL_MEMES,
    'CHANNEL_MEDIA': CHANNEL_MEDIA,
    'CHANNEL_NEW_VIDEOS': CHANNEL_NEW_VIDEOS,
    'CHANNEL_NEW_FEDI': CHANNEL_NEW_FEDI,
    'CHANNEL_NEW_TIKTOK': CHANNEL_NEW_TIKTOK,
    'CHANNEL_MODERATION': CHANNEL_MODERATION,
    'FEDI_INSTANCE': FEDI_INSTANCE,
    'FEDI_USER_ID': FEDI_USER_ID,
    'FEDI_TOKEN': FEDI_TOKEN,
    'FORGEJO_INSTANCE': FORGEJO_INSTANCE,
    'FORGEJO_DEFAULT_USER': FORGEJO_DEFAULT_USER,
    'FORGEJO_TOKEN': FORGEJO_TOKEN,
    'YT_LINK': YT_LINK,
    'TT_LINK': TT_LINK,
    'WEB_SERVER_URL': WEB_SERVER_URL,
    'WEB_SERVER_CODE': WEB_SERVER_CODE
})
