import os

import sentry_sdk

VERSION = "2025.05.25"

DISCORD_TOKEN = os.getenv("DISCORD_TOKEN")
SENTRY_DSN = os.getenv("SENTRY_DSN")

GUILD = os.getenv("GUILD")
OWNER = os.getenv("OWNER")

ROLE_HE = os.getenv("ROLES_HE")
ROLE_SHE = os.getenv("ROLES_SHE")
ROLE_THEY = os.getenv("ROLES_THEY")
ROLE_ONE = os.getenv("ROLES_ONE")
ROLE_IT = os.getenv("ROLES_IT")
ROLE_ANY = os.getenv("ROLES_ANY")
ROLE_ASK = os.getenv("ROLES_ASK")
ROLE_NAME = os.getenv("ROLES_NAME")

ROLE_VIDEOS = os.getenv("ROLE_NOTIF_VIDEOS")
ROLE_STREAMS = os.getenv("ROLE_NOTIF_STREAMS")
ROLE_TIKTOK = os.getenv("ROLE_NOTIF_TIKTOK")
ROLE_FEDI = os.getenv("ROLE_NOTIF_FEDI")
ROLE_SERVER = os.getenv("ROLE_NOTIF_SERVER")

ROLE_VERIFIED = os.getenv("ROLES_VERIFIED")

ROLE_MOD = os.getenv("ROLES_MOD")

CHANNEL_GENERAL = os.getenv("CHANNEL_GENERAL")
CHANNEL_MEMES = os.getenv("CHANNEL_MEMES")
CHANNEL_MEDIA = os.getenv("CHANNEL_MEDIA")
CHANNEL_ROLES = os.getenv("CHANNEL_ROLES")
CHANNEL_RULES = os.getenv("CHANNEL_RULES")
CHANNEL_SUGGESTIONS = os.getenv("CHANNEL_SUGGESTIONS")

CHANNEL_NEW_VIDEOS = os.getenv("CHANNEL_NEW_VIDEOS")
CHANNEL_NEW_FEDI = os.getenv("CHANNEL_NEW_FEDI")
CHANNEL_NEW_TIKTOK = os.getenv("CHANNEL_NEW_TIKTOK")

CHANNEL_MODERATION = os.getenv("CHANNEL_MODERATION")

VERIFICATION_GROUP_ID = os.getenv("VERIFICATION_GROUP_ID")

FEDI_INSTANCE = os.getenv("FEDI_INSTANCE")
FEDI_USER_ID = os.getenv("FEDI_USER_ID")
FEDI_TOKEN = os.getenv("FEDI_TOKEN")

YT_LINK = os.getenv("YT_LINK")
TT_LINK = os.getenv("TT_LINK")

def validate_values(l: dict[str, str | None]):
    for k, v in l.items():
        if v is None:
            print(f"CONSTANTS: The constant value for {k} is NOT set!")
            sentry_sdk.capture_message(f"CONSTANTS: The constant value for {k} is NOT set!")

validate_values({
    'DISCORD_TOKEN': DISCORD_TOKEN,
    'SENTRY_DSN': SENTRY_DSN,
    'GUILD': GUILD,
    'OWNER': OWNER,
    'ROLE_HE': ROLE_HE,
    'ROLE_SHE': ROLE_SHE,
    'ROLE_THEY': ROLE_THEY,
    'ROLE_ONE': ROLE_ONE,
    'ROLE_IT': ROLE_IT,
    'ROLE_ANY': ROLE_ANY,
    'ROLE_ASK': ROLE_ASK,
    'ROLE_NAME': ROLE_NAME,
    'ROLE_VIDEOS': ROLE_VIDEOS,
    'ROLE_STREAMS': ROLE_STREAMS,
    'ROLE_TIKTOK': ROLE_TIKTOK,
    'ROLE_FEDI': ROLE_FEDI,
    'ROLE_SERVER': ROLE_SERVER,
    'ROLE_VERIFIED': ROLE_VERIFIED,
    'ROLE_MOD': ROLE_MOD,
    'CHANNEL_GENERAL': CHANNEL_GENERAL,
    'CHANNEL_MEMES': CHANNEL_MEMES,
    'CHANNEL_MEDIA': CHANNEL_MEDIA,
    'CHANNEL_ROLES': CHANNEL_ROLES,
    'CHANNEL_RULES': CHANNEL_RULES,
    'CHANNEL_SUGGESTIONS': CHANNEL_SUGGESTIONS,
    'CHANNEL_NEW_VIDEOS': CHANNEL_NEW_VIDEOS,
    'CHANNEL_NEW_FEDI': CHANNEL_NEW_FEDI,
    'CHANNEL_NEW_TIKTOK': CHANNEL_NEW_TIKTOK,
    'CHANNEL_MODERATION': CHANNEL_MODERATION,
    'VERIFICATION_GROUP_ID': VERIFICATION_GROUP_ID,
    'FEDI_INSTANCE': FEDI_INSTANCE,
    'FEDI_USER_ID': FEDI_USER_ID,
    'FEDI_TOKEN': FEDI_TOKEN,
    'YT_LINK': YT_LINK,
    'TT_LINK': TT_LINK
})
