[project]
name = "mldchan-ai"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.10"
dependencies = [
    "aiohttp==3.11.18",
    "certifi==2025.4.26",
    "requests==2.32.3",
    "sentry-sdk==2.27.0",
    "yt-dlp==2025.5.10.232848.dev0",
]
